#!/usr/bin/env bash
# Script to diplay:
#  To infinity and beyond
#  with a sleep in between
#  I anm invincible!!! when receiving a SIGTERM signal

trap 'echo "I am invincible"' SIGTERM
while true
do
	echo "To infinity and beyond"
		sleep 2
done
